[manual_stepper selector_stepper] #6, selector
enable_pin: !PD4
step_pin: PE2
dir_pin: PE3
rotation_distance: 40
microsteps: 16 			# Don't need high fidelity
full_steps_per_rotation: 200	# 200 for 1.8 degree, 400 for 0.9 degree
velocity: 200
accel: 600
#
# Select the endstop switch physical (for normal selector) or virtual (sensorless selector homing)
#endstop_pin: tmc2209_selector_stepper:virtual_endstop	# Uncomment for sensorless selector homing
endstop_pin: ^{selector_endstop_pin}			# Uncomment for physical homing option (default)

# SELECTOR STEPPER  --------------------------------------------------------------------------------------------------------
[tmc2209 manual_stepper selector_stepper] #6, selector
uart_pin: PE1
run_current: 0.5		# NEMA17 motor
hold_current: 0.3		# Can be small if not using sensorless selector
# interpolate: True
# sense_resistor: 0.110
stealthchop_threshold: 0	# 999999 to enable stealthChop
#
# Uncomment the lines below if you want to use sensorless selector homing
# (and configure ercf_parameters.cfg correctly)
# or comment out if using physical endstop switch (default)
diag_pin: ^{selector_diag_pin}		# Set to MCU pin connected to TMC DIAG pin
driver_SGTHRS: 128		# 255 is most sensitive value, 0 is least sensitive

[manual_stepper gear_stepper] #7, feeder
enable_pin: !PE0
step_pin: PE6
dir_pin: PA14
rotation_distance: 22.7316868		# Bondtech 5mm Drive Gears. Must be manually verified and tuned.
microsteps: 16 				# Recommend 8 or 16. Try both to avoid Klipper 'Timer too close' error (also try adjusting num_moves)
full_steps_per_rotation: 200		# 200 for 1.8 degree, 400 for 0.9 degree
velocity: 50
accel: 400
# Uncomment if you want to use sensorless SELECTOR with the ERCF EASY BRD (yes, this is on the gear stepper!)
# This should be the pin of the physical selector endstop and is used to determine the difference between the true
# endstop and a blockage preventing selector movement. Don't forget to set 'sensorless_selector: 0' in ercf_parameters.cfg
#endstop_pin: ^{gear_endstop_pin}	# Comment if using physical endstop switch (default)

[tmc2209 manual_stepper gear_stepper] #7, feeder
uart_pin: {gear_uart_pin}
uart_address: 0
interpolate: True
run_current: 0.5			# NEMA14 motor
hold_current: 0.1			# Can be small
sense_resistor: 0.110
stealthchop_threshold: 0		# 999999 to enable stealthChop

# SELECTOR SERVO -----------------------------------------------------------------------------------------------------------
[ercf_servo ercf_servo]
pin: {servo_pin}
maximum_servo_angle: 180
minimum_pulse_width: 0.00085
maximum_pulse_width: 0.00215


## ENCODER -----------------------------------------------------------------------------------------------------------------
## The encoder_resolution is determined by running the ERCF_CALIBRATE_ENCODER. Be sure to read the manual
[ercf_encoder ercf_encoder]
encoder_pin: ^{encoder_pin}			# EASY-BRD: ^ercf:PA6, Flytech ERB: ^ercf:gpio22
encoder_resolution: 1.339226	# Set AFTER 'rotation_distance' is tuned for gear stepper (see manual)
extruder: extruder		# The extruder to track with for runout/clog detection

# These are advanced but settings for Automatic clog detection mode. Make sure you understand or ask questions on Discord
desired_headroom: 8.0		# The runout headroom that ERCF will attempt to maintain (closest ERCF comes to triggering runout)
average_samples: 4		# The "damping" effect of last measurement. Higher value means clog_length will be reduced more slowly


## TOOLHEAD SENSOR ---------------------------------------------------------------------------------------------------------
# Uncomment this section to enable toolhead sensor support
#
## ERCF Toolhead sensor START
#[filament_switch_sensor toolhead_sensor]
#pause_on_runout: False		# Must be False
#switch_pin: {toolhead_sensor_pin}
## ERCF Toolhead sensor END


